function com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit(){var Q='bootstrap',R='begin',S='gwt.codesvr.com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit=',T='gwt.codesvr=',U='com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit',qb='Failed to load ',rb='head',sb='meta',tb='name',ub='com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit::',vb='::',wb='gwt:property',xb='content',yb='=',zb='gwt:onPropertyErrorFn',Ab='Bad handler "',Bb='" for "gwt:onPropertyErrorFn"',Cb='gwt:onLoadErrorFn',Db='" for "gwt:onLoadErrorFn"',Eb='#',Fb='?',Gb='/',Hb='img',Ib='clear.cache.gif',Jb='baseUrl',Kb='com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit.nocache.js',Lb='base',Mb='//',Nb='locale',Ob='default',Pb='locale=',Qb=7,Rb='&',Sb='__gwt_Locale',Tb='_',Ub='Unexpected exception in locale detection, using default: ',Vb=2,Wb='selectingPermutation',Xb='com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit.devmode.js',Yb='es',Zb='45092C2194F34E98E458CCAC062724ED',$b='9356A0E6FB6BC8B79B3346477C021C77',_b='de',ac='FEFCAA8354C67117C16B7EE0855D8E93',bc=':',cc=10,dc='.cache.js',ec='link',fc='rel',gc='stylesheet',hc='href',ic='loadExternalRefs',jc='gwt/clean/clean.css',kc='end',lc='http:',mc='file:',nc='_gwt_dummy_',oc='__gwtDevModeHook:com.google.gwt.sample.stockwatcher.StockWatcherJUnit.JUnit',pc='Ignoring non-whitelisted Dev Mode URL: ',qc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__sendStats=t;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleName=U;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__errFn=null;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleBase=W;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__softPermutationId=X;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__computePropValue=null;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__getPropMap=null;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__installRunAsyncCode=function(){};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__gwtStartLoadingFragment=function(){return null};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__gwt_isKnownPropertyValue=function(){return false};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__errFn){n.onerror=function(){com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__errFn(pb,new Error(qb+code))}}r.getElementsByTagName(rb)[X].appendChild(n)}
com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__startLoadingFragment=function(a){return G(a)};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(sb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,db);if(j.indexOf(vb)>=X){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Jb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Lb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=X){var f=d.substring(e+Qb);var g=d.indexOf(Rb,e);if(g<X){g=d.length}b=d.substring(e+Qb,g)}}if(!b){b=__gwt_getMetaProperty(Nb)}if(!b){b=q[Sb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Nb,b)){var h=b.lastIndexOf(Tb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Ub+a)}q[Sb]=c;return b||Ob};l[Nb]={'de':X,'default':Y,'es':Vb};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__computePropValue=n;q.__gwt_activeModules[U].bindings=com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__getPropMap;t(Q,Wb);if(s()){return G(Xb)}var o;try{k([Yb],Zb);k([Ob],$b);k([_b],ac);o=i[n(Nb)];var p=o.indexOf(bc);if(p!=-1){j=parseInt(o.substring(p+Y),cc);o=o.substring(X,p)}}catch(a){}com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__softPermutationId=j;return G(o+dc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(ec);b.setAttribute(fc,gc);b.setAttribute(hc,G(a));r.getElementsByTagName(rb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(ic,R);c(jc);t(ic,kc)}
D();com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleBase=F();v[U].moduleBase=com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==lc||q.location.protocol==mc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=nc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=oc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(pc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+qc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(rb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,kc);C(J);return true}
com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit.succeeded=com_google_gwt_sample_stockwatcher_StockWatcherJUnit_JUnit();